# Generated by Django 3.2.3 on 2021-07-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210624_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='recipe_tag', to='recipes.Tag'),
        ),
    ]
