# Generated by Django 3.2.3 on 2021-07-16 11:23

import django.core.validators
from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(validators=[recipes.validators.value_is_russia]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[recipes.validators.value_is_russia]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_cooking',
            field=models.PositiveIntegerField(validators=[recipes.validators.value_is_not_null]),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
