# Generated by Django 3.2.3 on 2021-08-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchases',
            field=models.ManyToManyField(null=True, related_name='recipe_purchase', to='recipes.Recipe'),
        ),
    ]
