# Generated by Django 3.2.3 on 2021-08-09 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0012_alter_purchase_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchase', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchases',
            field=models.ManyToManyField(related_name='recipe_purchase', to='recipes.Recipe'),
        ),
    ]
